# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_learnerprofile_college_id_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. name@okaxis', max_length=50, null=True),
        ),
    ]
