# Generated by Django 5.2.8 on 2025-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trainerprofile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='college_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='college_ids/'),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='dl_image',
            field=models.ImageField(blank=True, null=True, upload_to='dl_scans/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='car_model',
            field=models.CharField(default='Not Set', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='dl_number',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
